name: Pull MongoDB Docker Image

on:
  push:
  workflow_dispatch:
    inputs:
      image_version:
        description: 'Specify MongoDB Docker image version'
        required: true
        default: '8'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: docker pull mongo:${{ github.event.inputs.image_version || 'latest' }}

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          docker tag mongo:${{ github.event.inputs.image_version || 'latest' }} mongo:company
